ex src/importGitHubActionsWorkflows.js << EOEX
%s/WORKFLOW_READ_TOKEN - DO NOT SPECIFY - POPULATED AUTOMATICALLY/$1/
wq
EOEX

ex src/importGitHubActionsRuns.js << EOEX
%s/WORKFLOW_READ_TOKEN - DO NOT SPECIFY - POPULATED AUTOMATICALLY/$1/
wq
EOEX
