name: Push to Google Apps Script

on:
  release:
    types: [ created ]
  workflow_dispatch: # enable manual execution

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use defined Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm build

    - name: Run tests
      run: npm test

    - name: Google Apps Script login
      uses: namaggarwal/clasp-token-action@v0.0.1
      with:
        client-id: ${{ secrets.OAUTH2_CLIENT_ID }}
        client-secret: ${{ secrets.OAUTH2_CLIENT_SECRET }}
        refresh-token: ${{ secrets.OAUTH2_REFRESH_TOKEN }}

    - name: Push to Google Apps Scripts
      run: |
        npm run updateConfigJson
        npm run claspPush
